"""
db/models.py
============
SQLAlchemy 2.0 ORM model definitions for StudyMate.

Tables
------
- spaces       : A broad learning area (e.g. "DSA Prep", "System Design").
- projects     : A focused learning journey inside a Space.
- threads      : A LangGraph conversation session inside a Project.
- documents    : A PDF uploaded by the student, linked to a thread.
- study_log    : An audit trail of study events.
- topics_cache : Cached extracted document topics.
- user_memories: Structured weak-topic / preference facts, scoped to a project.
- quiz_attempts: Append-only record of completed quiz scores, scoped to a project.

Design notes
------------
- SQLAlchemy 2.0 `Mapped` / `mapped_column` API for full static-type safety.
- All primary keys are string UUIDs (app-generated) for portability.
- `ondelete="CASCADE"` on FKs means deleting a parent row automatically
  removes all child rows at the DB level.
- Space/Project have no `owner_id` yet — that column will be added as nullable
  in a future auth migration. See Known Limitations in the implementation plan.
"""

from datetime import datetime
from enum import Enum

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum as SqlEnum,
    ForeignKey,
    Integer,
    String,
    func,
    Index,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from app.config import DEFAULT_USER_ID


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """Shared declarative base for all StudyMate ORM models."""
    pass


# ---------------------------------------------------------------------------
# users & user_sessions
# ---------------------------------------------------------------------------

class User(Base):
    """
    An authenticated StudyMate student or admin account.
    """
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    email: Mapped[str] = mapped_column(String, unique=True, nullable=False, index=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    password_hash: Mapped[str] = mapped_column(String, nullable=False)
    salt: Mapped[str] = mapped_column(String, nullable=False)
    role: Mapped[str] = mapped_column(String, nullable=False, default="student")
    is_demo: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # relationships
    spaces: Mapped[list["Space"]] = relationship(
        "Space", back_populates="owner", cascade="all, delete-orphan"
    )
    projects: Mapped[list["Project"]] = relationship(
        "Project", back_populates="owner", cascade="all, delete-orphan"
    )
    sessions: Mapped[list["UserSession"]] = relationship(
        "UserSession", back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<User id={self.id!r} email={self.email!r} role={self.role!r}>"


class UserSession(Base):
    """
    Active authentication session for a User.
    """
    __tablename__ = "user_sessions"

    token: Mapped[str] = mapped_column(String, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # relationship
    user: Mapped["User"] = relationship("User", back_populates="sessions")

    def __repr__(self) -> str:
        return f"<UserSession token=... user_id={self.user_id!r}>"


# ---------------------------------------------------------------------------
# spaces
# ---------------------------------------------------------------------------

class Space(Base):
    """
    A broad learning area grouping one or more Projects.

    Examples: "DSA Prep", "System Design", "Linear Algebra".
    Deleting a Space cascades to its Projects → Threads → Documents.
    """

    __tablename__ = "spaces"
    __table_args__ = (Index("ix_spaces_user_id", "user_id"),)

    id: Mapped[str] = mapped_column(String, primary_key=True)
    """UUID string, generated by the application before insert."""

    user_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, default=DEFAULT_USER_ID
    )
    """Owner user ID — enforces user isolation."""

    name: Mapped[str] = mapped_column(String, nullable=False)
    """Human-readable label shown in the sidebar."""

    description: Mapped[str | None] = mapped_column(String, nullable=True)
    """Optional tagline for the space."""

    archived: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    """Soft-delete flag. Archived spaces are hidden from the sidebar."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    # relationships
    owner: Mapped["User"] = relationship("User", back_populates="spaces")
    projects: Mapped[list["Project"]] = relationship(
        "Project", back_populates="space", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Space id={self.id!r} name={self.name!r} user_id={self.user_id!r}>"


# ---------------------------------------------------------------------------
# projects
# ---------------------------------------------------------------------------

class Project(Base):
    """
    A focused learning journey inside a Space.

    A Project owns one or more Threads (conversation sessions), its uploaded
    Documents, quiz/flashcard history, and study-progress records.
    Deleting a Project cascades to all of its Threads → Documents.
    """

    __tablename__ = "projects"
    __table_args__ = (
        Index("ix_projects_space_id", "space_id"),
        Index("ix_projects_user_id", "user_id"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True)
    """UUID string, generated by the application before insert."""

    user_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, default=DEFAULT_USER_ID
    )
    """Owner user ID — matches owning Space's user_id."""

    space_id: Mapped[str] = mapped_column(
        String, ForeignKey("spaces.id", ondelete="CASCADE"), nullable=False
    )
    """Foreign key back to the owning Space."""

    name: Mapped[str] = mapped_column(String, nullable=False)
    """Human-readable project name (e.g. 'Week 3 Review')."""

    description: Mapped[str | None] = mapped_column(String, nullable=True)
    """Optional short description."""

    archived: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    """Soft-delete flag."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    # relationships
    owner: Mapped["User"] = relationship("User", back_populates="projects")
    space: Mapped["Space"] = relationship("Space", back_populates="projects")
    threads: Mapped[list["Thread"]] = relationship(
        "Thread", back_populates="project", cascade="all, delete-orphan"
    )
    user_memories: Mapped[list["UserMemory"]] = relationship(
        "UserMemory", back_populates="project", cascade="all, delete-orphan"
    )
    quiz_attempts: Mapped[list["QuizAttempt"]] = relationship(
        "QuizAttempt", back_populates="project", cascade="all, delete-orphan"
    )
    concept_masteries: Mapped[list["ConceptMastery"]] = relationship(
        "ConceptMastery", back_populates="project", cascade="all, delete-orphan"
    )
    concept_mastery_history: Mapped[list["ConceptMasteryHistory"]] = relationship(
        "ConceptMasteryHistory", back_populates="project", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Project id={self.id!r} name={self.name!r}>"


# ---------------------------------------------------------------------------
# threads
# ---------------------------------------------------------------------------

class Thread(Base):
    """
    A LangGraph conversation session within a Project.

    A Thread groups a set of uploaded Documents and the chat history
    associated with them. Deleting a Thread cascades to its Documents
    and StudyLog rows.

    Note: thread_id is the LangGraph conversation key (baked into checkpoints)
    and is intentionally kept separate from project_id.
    """

    __tablename__ = "threads"
    __table_args__ = (Index("ix_threads_project_id", "project_id"),)

    id: Mapped[str] = mapped_column(String, primary_key=True)
    """UUID string, generated by the application before insert."""

    project_id: Mapped[str] = mapped_column(
        String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    """Foreign key back to the owning Project."""

    title: Mapped[str] = mapped_column(String, nullable=False)
    """Human-readable label shown in the sidebar (e.g. 'CS101 Week 3')."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    # relationships
    project: Mapped["Project"] = relationship("Project", back_populates="threads")
    documents: Mapped[list["Document"]] = relationship(
        "Document", back_populates="thread", cascade="all, delete-orphan"
    )
    study_log: Mapped[list["StudyLog"]] = relationship(
        "StudyLog", back_populates="thread", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Thread id={self.id!r} title={self.title!r}>"


# ---------------------------------------------------------------------------
# documents
# ---------------------------------------------------------------------------

class Document(Base):
    """
    Represents a PDF (or other source document) uploaded by the student.

    Each document stores metadata about the file and the path to the FAISS
    vector index built from its chunks. The vectorstore_path is used by the
    RAG retriever to load the correct index at query time.
    """

    __tablename__ = "documents"
    __table_args__ = (Index("ix_documents_thread_id", "thread_id"),)

    id: Mapped[str] = mapped_column(String, primary_key=True)
    """UUID string, generated by the application before insert."""

    thread_id: Mapped[str] = mapped_column(
        String, ForeignKey("threads.id", ondelete="CASCADE"), nullable=False
    )
    """Foreign key back to the owning thread."""

    filename: Mapped[str] = mapped_column(String, nullable=False)
    """Original filename as uploaded (e.g. 'lecture3.pdf')."""

    vectorstore_path: Mapped[str] = mapped_column(String, nullable=False)
    """
    Absolute (or workspace-relative) path to the directory containing the
    persisted FAISS index files (index.faiss + index.pkl).
    Convention: vectorstores/<thread_id>/<document_id>/
    """

    page_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    """Number of pages in the source PDF."""

    chunk_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    """Number of text chunks ingested into the vector store."""

    index_status: Mapped[str] = mapped_column(String, nullable=False, default="uploaded")
    """Async indexing state: 'uploaded' | 'indexing' | 'ready' | 'error'."""

    index_error: Mapped[str | None] = mapped_column(String, nullable=True)
    """Terminal indexing error message, when indexing fails."""

    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    """Timestamp set by the DB at INSERT time."""

    # relationships
    thread: Mapped["Thread"] = relationship("Thread", back_populates="documents")

    def __repr__(self) -> str:
        return f"<Document id={self.id!r} filename={self.filename!r}>"


class FlashcardReview(Base):
    """Latest learning status for one student's project flashcard."""

    __tablename__ = "flashcard_reviews"
    __table_args__ = (
        Index("ix_flashcard_reviews_scope", "user_id", "project_id", "learning_status"),
        Index("ix_flashcard_reviews_card", "user_id", "project_id", "document_id", "front"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    project_id: Mapped[str] = mapped_column(String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    document_id: Mapped[str | None] = mapped_column(String, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    front: Mapped[str] = mapped_column(String, nullable=False)
    back: Mapped[str | None] = mapped_column(String, nullable=True)
    topic: Mapped[str | None] = mapped_column(String, nullable=True)
    learning_status: Mapped[str] = mapped_column(String, nullable=False, default="still_learning")
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())


# ---------------------------------------------------------------------------
# study_log
# ---------------------------------------------------------------------------

class StudyLog(Base):
    """
    Append-only event log recording what the student studied in each thread.

    Every time the agent performs a meaningful action (answering a question,
    generating a quiz, etc.) we write one row here. This powers future
    analytics dashboards and the RAGAS evaluation pipeline.
    """

    __tablename__ = "study_log"
    __table_args__ = (
        Index("ix_study_log_thread_id", "thread_id"),
        Index("ix_study_log_event_type", "event_type"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    """Auto-incrementing integer PK — fine for a log table."""

    thread_id: Mapped[str] = mapped_column(
        String, ForeignKey("threads.id", ondelete="CASCADE"), nullable=False
    )

    document_id: Mapped[str | None] = mapped_column(
        String, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    """
    Optional: which document triggered this event.
    NULL for events like web-search answers that don't originate from a
    specific uploaded document.
    """

    event_type: Mapped[str] = mapped_column(String, nullable=False)
    """
    Machine-readable event kind. Allowed values (enforced at app layer):
      - "question_answered"
      - "quiz_generated"
      - "flashcards_generated"
      - "web_search_used"
    """

    topic: Mapped[str | None] = mapped_column(String, nullable=True)
    """
    Short human-readable description of what was studied, e.g.
    'Newton's laws of motion' or 'Chapter 4 review'.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # relationships
    thread: Mapped["Thread"] = relationship("Thread", back_populates="study_log")

    def __repr__(self) -> str:
        return (
            f"<StudyLog id={self.id} thread={self.thread_id!r} "
            f"event={self.event_type!r}>"
        )


# ---------------------------------------------------------------------------
# topics_cache
# ---------------------------------------------------------------------------

class TopicsCache(Base):
    """Cached extracted document topics; invalidated by a new document ID."""

    __tablename__ = "topics_cache"

    document_id: Mapped[str] = mapped_column(
        String, ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True
    )
    topics_json: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


# ---------------------------------------------------------------------------
# user_memories
# ---------------------------------------------------------------------------

class MemoryFactType(str, Enum):
    """Small, project-scoped memory categories; never stores raw transcripts."""

    WEAK_TOPIC = "weak_topic"
    STUDIED_TOPIC = "studied_topic"
    PREFERENCE = "preference"


class UserMemory(Base):
    """
    One compact, structured fact carried across threads within a Project.

    Previously keyed off user_id only (cross-project). Now scoped to a
    project_id so DSA Prep weak topics don't bleed into System Design.
    """

    __tablename__ = "user_memories"
    __table_args__ = (
        Index("ix_user_memories_project_created", "project_id", "created_at"),
        Index("ix_user_memories_user_created", "user_id", "created_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(String, nullable=False, default=DEFAULT_USER_ID)
    project_id: Mapped[str] = mapped_column(
        String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    """Foreign key to the owning Project — enforces data isolation."""

    fact_type: Mapped[MemoryFactType] = mapped_column(SqlEnum(MemoryFactType), nullable=False)
    topic: Mapped[str | None] = mapped_column(String, nullable=True)
    reason: Mapped[str] = mapped_column(String, nullable=False, default="quiz_score")
    detail: Mapped[str] = mapped_column(String, nullable=False)
    document_id: Mapped[str | None] = mapped_column(
        String, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # relationships
    project: Mapped["Project"] = relationship("Project", back_populates="user_memories")


# ---------------------------------------------------------------------------
# quiz_attempts
# ---------------------------------------------------------------------------

class QuizAttempt(Base):
    """
    One factual, project-scoped record of a completed quiz attempt.

    Retains the document identifier even if the document is later deleted,
    so historical scores remain accurate.
    """

    __tablename__ = "quiz_attempts"
    __table_args__ = (
        Index("ix_quiz_attempts_project_created", "project_id", "created_at"),
        Index("ix_quiz_attempts_user_created", "user_id", "created_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(String, nullable=False, default=DEFAULT_USER_ID)
    project_id: Mapped[str] = mapped_column(
        String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    """Foreign key to the owning Project — enforces data isolation."""

    document_id: Mapped[str] = mapped_column(String, nullable=False)
    topic: Mapped[str] = mapped_column(String, nullable=False)
    correct_count: Mapped[int] = mapped_column(Integer, nullable=False)
    total_questions: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # relationships
    project: Mapped["Project"] = relationship("Project", back_populates="quiz_attempts")


# ---------------------------------------------------------------------------
# concept_mastery
# ---------------------------------------------------------------------------

class ConceptMastery(Base):
    """
    Current EMA mastery score for one concept within a project.

    Keyed by (project_id, concept) where concept is the lowercased,
    stripped form of QuizAttempt.topic.  One row per concept per project —
    updated in-place on every quiz submission using an atomic UPSERT so
    concurrent submissions cannot produce a lost-update race condition.

    Formula (α = 0.4 exponential moving average):
        new_score = 0.4 × session_pct + 0.6 × old_score
    Initial old_score for a brand-new concept defaults to 50 (neutral prior).

    Isolation guarantee: the UNIQUE constraint on (project_id, concept) means
    "recursion" in Project A and "recursion" in Project B are always separate
    rows that can never share state.
    """

    __tablename__ = "concept_mastery"
    __table_args__ = (
        Index("ix_concept_mastery_project_concept", "project_id", "concept", unique=True),
        Index("ix_concept_mastery_project", "project_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    project_id: Mapped[str] = mapped_column(
        String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    """Foreign key to the owning Project — cascade delete wipes mastery with the project."""

    concept: Mapped[str] = mapped_column(String, nullable=False)
    """Normalized concept name: topic.strip().lower(). Free-text, no canonical list."""

    score: Mapped[float] = mapped_column(nullable=False, default=50.0)
    """Current EMA mastery score, range 0.0–100.0."""

    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    """Total number of quiz attempts that have contributed to this score."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # relationships
    project: Mapped["Project"] = relationship("Project", back_populates="concept_masteries")


# ---------------------------------------------------------------------------
# concept_mastery_history
# ---------------------------------------------------------------------------

class ConceptMasteryHistory(Base):
    """
    Append-only time-series of mastery score snapshots.

    One row is INSERTed after every quiz submission alongside the UPSERT to
    concept_mastery.  This table is never updated — only inserted into — so
    Growth Analysis can compute score trends over time without needing a
    second migration to retrofit history.
    """

    __tablename__ = "concept_mastery_history"
    __table_args__ = (
        Index("ix_cmh_project_concept_recorded", "project_id", "concept", "recorded_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    project_id: Mapped[str] = mapped_column(
        String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    concept: Mapped[str] = mapped_column(String, nullable=False)
    score: Mapped[float] = mapped_column(nullable=False)
    """EMA score at the moment this snapshot was recorded."""

    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    project: Mapped["Project"] = relationship("Project", back_populates="concept_mastery_history")
