"""Pydantic contracts for document-grounded quiz generation and open-ended grading."""

from typing import Literal

from pydantic import BaseModel, Field


class QuizQuestion(BaseModel):
    """One quiz question grounded in an uploaded document (MCQ or open-ended)."""

    question: str
    question_type: Literal["mcq", "open_ended"] = "mcq"
    options: list[str] | None = None
    correct_index: int | None = None
    explanation: str | None = None
    source_citation: str | None = None
    grading_token: str | None = None



class QuizGenerateRequest(BaseModel):
    """Parameters selecting document context and quiz characteristics."""

    document_id: str = Field(min_length=1)
    topic: str = Field(min_length=1)
    num_questions: int = Field(default=10, ge=1, le=25)
    difficulty: Literal["easy", "medium", "hard"] = "medium"
    question_type: Literal["mcq", "open_ended", "mixed"] = "mcq"


class QuizGenerateResponse(BaseModel):
    """Structured quiz result consumable by a quiz workspace."""

    type: Literal["tool_result"] = "tool_result"
    tool: Literal["quiz"] = "quiz"
    document_id: str
    topic: str
    difficulty: str
    questions: list[QuizQuestion]


class OpenEndedGradeEvaluation(BaseModel):
    """Structured evaluation generated by the LLM for an open-ended student answer."""

    understanding: Literal["excellent", "good", "partial", "poor"]
    accuracy: Literal["high", "moderate", "low", "incorrect"]
    relevance: Literal["direct", "tangential", "irrelevant"]
    key_concepts_covered: list[str] = Field(
        default_factory=list,
        description="Key conceptual elements correctly addressed by the student",
    )
    missing_concepts: list[str] = Field(
        default_factory=list,
        description="Essential conceptual points omitted or misunderstood",
    )
    feedback: str = Field(
        description="Constructive explanation of what the learner understood and what is missing",
    )


class OpenEndedGradeRequest(BaseModel):
    """Student submission for an open-ended quiz question."""

    project_id: str = Field(min_length=1)
    document_id: str = Field(min_length=1)
    topic: str = Field(min_length=1)
    question: str = Field(min_length=1)
    user_answer: str = Field(min_length=1)
    grading_token: str = Field(min_length=1)


class OpenEndedGradeResponse(BaseModel):
    """Graded result and qualitative feedback for an open-ended question."""

    score: float = Field(ge=0.0, le=100.0)
    evaluation: OpenEndedGradeEvaluation
    topic: str
